apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  namespace: default
  labels:
    kustomize.toolkit.fluxcd.io/name: flux-system
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: frontend
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 9898
  selector:
    app: frontend
  type: LoadBalancer
status:
  loadBalancer: {}